package com.clhs.score.analytics

object AnalyticsEvents {
    const val APP_OPEN_ROUTE = "app_open_route"
    const val LOGIN_START = "login_start"
    const val LOGIN_RESULT = "login_result"
    const val LOGOUT = "logout"
    const val BIOMETRIC_UNLOCK_RESULT = "biometric_unlock_result"
    const val GRADE_STRUCTURE_LOAD = "grade_structure_load"
    const val GRADE_QUERY = "grade_query"
    const val SCHEDULE_OPEN = "schedule_open"
    const val SCHEDULE_QUERY = "schedule_query"
    const val SCHEDULE_WIDGET_SETTINGS_SAVE = "schedule_widget_settings_save"
    const val NOTIFICATION_TOGGLE = "notification_toggle"
    const val NOTIFICATION_PROMPT_ACTION = "notification_prompt_action"
    const val GRADE_REMINDER_START = "grade_reminder_start"
    const val GRADE_REMINDER_STOP = "grade_reminder_stop"
    const val GRADE_REMINDER_NOTIFICATION_OPEN = "grade_reminder_notification_open"
    const val EXPORT_GRADES = "export_grades"
    const val UPDATE_CHECK = "update_check"
    const val SUBJECT_TREND_LOAD = "subject_trend_load"
    const val SCORE_SIMULATOR_USED = "score_simulator_used"
    const val FEATURE_OPEN = "feature_open"
}

object AnalyticsParams {
    const val ACTION = "action"
    const val CACHED = "cached"
    const val ENABLED = "enabled"
    const val ERROR_TYPE = "error_type"
    const val EXAM_COUNT_BUCKET = "exam_count_bucket"
    const val FEATURE = "feature"
    const val FAILURE_REASON = "failure_reason"
    const val LOCKED = "locked"
    const val METHOD = "method"
    const val MODE = "mode"
    const val REASON = "reason"
    const val RESULT = "result"
    const val SCREEN = "screen"
    const val SELECTION_COUNT_BUCKET = "selection_count_bucket"
    const val SHOW_CLASSROOM = "show_classroom"
    const val SHOW_TEACHER = "show_teacher"
    const val SHOW_TIME = "show_time"
    const val SOURCE = "source"
    const val SUBJECT_COUNT = "subject_count"
    const val SUBJECT_COUNT_BUCKET = "subject_count_bucket"
    const val SYSTEM_PERMISSION = "system_permission"
    const val TRIGGER = "trigger"
    const val YEAR_COUNT = "year_count"
}

object AnalyticsValues {
    const val ACTION_AUTO_DISABLED = "auto_disabled"
    const val ACTION_DISMISS = "dismiss"
    const val ACTION_OPEN_SETTINGS = "open_settings"
    const val FEATURE_SCHEDULE = "schedule"
    const val FEATURE_SCORE_SIMULATOR = "score_simulator"
    const val FEATURE_SETTINGS = "settings"
    const val FEATURE_SUBJECT_TREND = "subject_trend"
    const val METHOD_BIOMETRIC = "biometric"
    const val METHOD_DEMO = "demo"
    const val METHOD_PIN = "pin"
    const val METHOD_WEBVIEW = "webview"
    const val MODE_CLASS = "class"
    const val PERMISSION_BLOCKED = "blocked"
    const val PERMISSION_GRANTED = "granted"
    const val PERMISSION_NOT_REQUIRED = "not_required"
    const val REASON_BATTERY = "battery"
    const val REASON_FAILURE = "failure"
    const val REASON_LOGOUT = "logout"
    const val REASON_NO_EXAM = "no_exam"
    const val REASON_PERMISSION = "permission"
    const val REASON_UNKNOWN = "unknown"
    const val REASON_USER = "user"
    const val RESULT_AVAILABLE = "available"
    const val RESULT_CANCELLED = "cancelled"
    const val RESULT_EMPTY = "empty"
    const val RESULT_ERROR = "error"
    const val RESULT_FAILURE = "failure"
    const val RESULT_INVALIDATED = "invalidated"
    const val RESULT_NOT_AVAILABLE = "not_available"
    const val RESULT_SUCCESS = "success"
    const val SOURCE_GRADE_REMINDER = "grade_reminder"
    const val SOURCE_LAUNCHER = "launcher"
    const val SOURCE_LOCK_SCREEN = "lock_screen"
    const val SOURCE_NOTIFICATION_UPDATE = "notification_update"
    const val SOURCE_SETTINGS = "settings"
    const val SOURCE_TAB = "tab"
    const val SOURCE_WIDGET_SCHEDULE = "widget_schedule"
    const val TRIGGER_EXAM_SELECT = "exam_select"
    const val TRIGGER_INITIAL = "initial"
    const val TRIGGER_MANUAL = "manual"
    const val TRIGGER_NOTIFICATION = "notification"
    const val TRIGGER_REFRESH = "refresh"
    const val TRIGGER_REMINDER_TARGET = "reminder_target"
    const val TRIGGER_YEAR_SELECT = "year_select"
}
